server:
  port: 9090

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/usuarios/**

        - id: ms-hoteles
          uri: lb://ms-hoteles
          predicates:
            - Path=/api/hoteles/**

        - id: ms-vuelos
          uri: lb://ms-vuelos
          predicates:
            - Path=/api/vuelos/**

        - id: ms-destinos
          uri: lb://ms-destinos
          predicates:
            - Path=/api/destinos/**

        - id: ms-paquetes
          uri: lb://ms-paquetes
          predicates:
            - Path=/api/paquetes/**

        - id: ms-reservas-hotel
          uri: lb://ms-reservas-hotel
          predicates:
            - Path=/api/reservas-hotel/**

        - id: ms-reservas-vuelo
          uri: lb://ms-reservas-vuelo
          predicates:
            - Path=/api/reservas-vuelo/**

        - id: ms-pagos
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**

        - id: ms-resenas
          uri: lb://ms-resenas
          predicates:
            - Path=/api/resenas/**

        - id: ms-notificaciones
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG